name: docker image ci

on:
  push:
    tags: [ "*v" ]
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag friddlecopper/lark-gpt-search:${{github.ref_name}}
      
    - name: push images
      run: docker push friddlecopper/lark-gpt-search:${{github.ref_name}}
